#!/data/data/com.termux/files/usr/bin/bash
#? |-----------------------------------------------------------------------------------------------|
#? |  init                                                                                         |
#? |                                                                                               |
#? |  Copyright (c) 2020 Belikhun. All right reserved                                              |
#? |  Licensed under the MIT License. See LICENSE in the project root for license information.     |
#? |-----------------------------------------------------------------------------------------------|

set -e

cat sudo > /data/data/com.termux/files/usr/bin/sudo
chmod 777 /data/data/com.termux/files/usr/bin/sudo

apt update
pkg upgrade
apt install openssh
apt install git
pkg install ncurses-utils
pkg install curl
pkg install python

pip3 install -r requirements.txt

echo -e "\033[1;32m✓\033[0m Cài Đặt Thành Công!"